# Generated by Django 2.2.10 on 2020-06-29 14:25

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200629_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
