# Generated by Django 2.2.10 on 2020-06-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200630_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
